---
name: Run Go tests
on:
  push:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: test

permissions:
  contents: read
  id-token: write

jobs:
  terratest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24
      - name: Verify Docker is installed
        run: docker --version
      - name: Run Terratest
        run: go test -v ./...